### ISSUE TITLE
Throwing an error with the json data attached would be easier for the UI to parse.  

### ISSUE THREAD

**Issue by BryanFriestad** [TankGameOrg/engine#11]
Throwing an error with the json data attached would be easier for me to parse.  That's probably a separate issue though.

_Originally posted by @ryan3r in https://github.com/TankGameOrg/engine/pull/9#discussion_r1582373473_

**Comment by ryan3r** [comment]
This can probably be closed.  Recent versions of the engine have a more useful error message.  

`throw new Error(String.format("Rule %s has cooldown of %d seconds but only waited %d seconds", name, cooldown, elapsed));`

@BryanFriestad @TrevorBrunette

**Comment by TrevorBrunette** [comment]
Closing as no change. Rules should never fail with an exception. All requisites should be checked with preconditions. Anything else is user error.
