### ISSUE TITLE
Bug: Dead tanks that receive a life are still on the council

### ISSUE THREAD

**Issue by BryanFriestad** [TankGameOrg/engine#37]
I noticed by code inspection that the only time players are ever removed from the councilors list is when they are being promoted to senators. When a dead (but not destroyed) tank is granted a life by the council, they should be removed from said council. Otherwise, they will continue to be able to perform council actions and affect council base income and the armistice vote in some game versions.

```java
public static PlayerActionRule<Council> GetRuleCofferCostGrantLife(int cost)
    {
        return new PlayerActionRule<>(
            PlayerRules.ActionKeys.GRANT_LIFE,
            (s, c, n) -> c.getCoffer() >= cost,
            (s, c, n) -> {
                c.setCoffer(c.getCoffer() - cost);
                Tank t = toType(n[0], Tank.class);
                if (t.isDead()) {
                    t.setDead(false);
                    t.setDurability(1);
                    // TODO: something here probably
                } else {
                    t.setDurability(t.getDurability() + 1);
                }
            },
            new TankRange<Council>("target")
        );
    }
```

This above code is _probably_ all that needs to be done, but please make sure and add some UT for this rule. Also, make sure that senators cannot be granted a life (I think they are not valid target because their tank is replaced with an empty unit).

**Comment by TrevorBrunette** [comment]
Fixed the formatting. Use ` ``` ` to indicate a multiline codeblock. You can specify the language with something like ` ```java ` as the beginning tag.

**Comment by BryanFriestad** [comment]
Neat, thanks for informing me!
