### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by BryanFriestad** [TankGameOrg/engine#63]
- There are 3 teams in v5.
- At the start of the game in v5, everyone is "unaffiliated".
- At any time you can take an action called "Join Team X". It has no cost, but may be affected by cooldowns.
- Once you joined a team, you lose the ability to join the other teams, but gain a new action called "Betray Team X".
- If you betray that team, you become unaffiliated again. You can now join the other teams, but cannot rejoin team X.
- Once you have betrayed all teams, cannot join a team and are forced to remain unaffiliated.
- Team names are more of a UI/Display configuration

**Comment by ryan3r** [comment]
> At any time you can take an action called "Join Team X". It has no cost, but may be affected by cooldowns.
This should probably be implemented as one action "join team" with a team parameter

> Once you joined a team, you lose the ability to join the other teams, but gain a new action called "Betray Team X".
In the same vein this could probably be "Betray Team" or "Betray Current Team"

> Team names are more of a UI/Display configuration
The names would have to be in the engine/initial state to make the join team command work.  The rest can be added in the UI.

**Comment by TrevorBrunette** [comment]
Will be closed by #95 which adds a team attribute and a team win condition. Deferring a rule to allow team changes.
