### ISSUE TITLE
Create Debug/Dev API+Ruleset

### ISSUE THREAD

**Issue by BryanFriestad** [TankGameOrg/engine#65]
We need to have a debug or development API and Ruleset, which handles all map features, rules, etc. so that we can easily test these things without affecting the existing APIs for v3 and v4

**Comment by ryan3r** [comment]
How would this work?
* shoot v3
* shoot v4
* shoot proposed
* ...

Could this be done by creating a v5 ruleset that duplicates v4 and then implementing v5 features one at at time?

**Comment by TrevorBrunette** [comment]
Already completed by #86.
