### ISSUE TITLE
Add Status Effects

### ISSUE THREAD

**Issue by BryanFriestad** [TankGameOrg/engine#7]
Various future game rules may apply "status effects" to tanks, which change them in many ways.

Status Effects will be applied by different triggers:
- Entering a space
- Being in a space at the start of a day
- Taking an action (anyone can be the target of the status effect, no matter who takes the action)
- As a result of some larger game event. Example: Player A and B are on Team Z. Player A enters Zone 1. Team Z gains control of Zone 1. A status effect is applied to all players on Team Z.
- Number of remaining players
- Number of game days elapsed

Status Effects can do many things to a tank:
- A status effect may affect one of the many tank "attributes"
- A status effect may enable that tank to take certain actions (that they could not without that status effect)
- A status effect may restrict that tank from taking certain actions
- A status effect may change the cost of taking an action. Example: Actions cost 4 gold instead of 3 gold.

Status Effect Duration:
- A status effect may have a "gameday"-based duration, after which they expire
- A status effect may be permanent
- A status effect may be indefinite, meaning it can be removed by some other event/trigger

List of Tank Attributes:
- Lives
- Max Lives
- Actions
- Actions/Day
- Max Actions
- Range
- Gold
- Max Gold
- Move speed
- Hit chance
- Attack Damage
- _This should be abstract enough to support changing attributes, new attributes, etc._

**Comment by BryanFriestad** [comment]
This request needs to be revisited. I'm not sure exactly what is needed for v5 anymore.

**Comment by TrevorBrunette** [comment]
Boolean tank "Attributes" are effectively status effects. Functionality can be implemented by any ruleset using conditional rules, tick rules, and player action rules. Closing as resolved.
